version: '3.8'
services:
    db:
        container_name: pg-container
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: toor
            POSTGRES_DB: taskmanagement
        ports:
            - "5432:5432"
    pgadmin:
        container_name: pgadmin4-container
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: toor
        ports:
            - "5050:80"